os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git
  - "export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH"
  - "flutter doctor"
  - "pub global activate flutter_plugin_tools"
# Testing script
script: 
#  - "./script/incremental_build.sh analyze"
  - "flutter test test/widget_test.dart"
sources: 
  - ubuntu-toolchain-r-test
before_deploy:
  - ./flutter/bin/flutter -v build apk
  - git config --local user.name "$GIT_RELEASE_USER_NAME"
  - git config --local user.email "$GIT_RELEASE_USER_EMAIL"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "build/app/outputs/apk/app.apk"
  skip_cleanup: true
  on:
    branch: master
cache: 
  directories: 
    - $HOME/.pub-cache    
