language: java
os:
  - linux
sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
before_deploy:
  - chmod +x ./.travis/publish.sh 
deploy:
  provider: script
  skip_cleanup: true
  script: '../.travis/publish.sh'
cache:
  directories:
    - $HOME/.pub-cache
branches:
only: [master]
