language: generic
os:
  - linux
sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
    packages:
      - libstdc++6
      - fonts-droid
install:
  - git clone https://github.com/flutter/flutter.git -b beta
$FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get
cache:
  directories:
    - $HOME/.pub-cache
branches:
only: [master]

jobs:
  include:
  - <<: *widget_tests
  - stage: build
  - stage: deploy
  
widget_tests: &widget_tests
  name: "Widget tests"
  script: flutter test test/widget_test.dart
