os: linux
language: android
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - pub global activate flutter_plugin_tools
script:
  - flutter test test/widget_test.dart
sources:
  - ubuntu-toolchain-r-test
before_deploy:
  - "./flutter/bin/flutter -v build apk"
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_API_KEY}
  file: build/app/outputs/apk/app.apk
  skip_cleanup: true
  on:
    repo: xym0112/FoodForThought
    branches:
      only:
        - master
cache:
  directories:
    - "$HOME/.pub-cache"
